#!/usr/bin/env python3
"""PreToolUse gate: the filesystem is the source of truth (iris-interop-skills).

`iris_doc(mode=put, content=...)` writes a class straight into the IRIS namespace. If the
class is not also on disk, the namespace becomes the only copy — it is outside git, outside
review, and it dies with the instance. This gate denies such a write when the project keeps
sources on disk and the class is missing from it.

Why this is not theoretical. Audited one student VM at the end of a workshop:

    28 classes on disk, 29 in IRIS, only 22 in common.

Seven classes existed ONLY in the namespace, and they were not scratch work — they were the
entire HL7 canonical flow (HL7ToCanonico -> MSG.PacienteCanonico -> CanonicoToMenu /
CanonicoToSOAP, plus AL1ToString and its test), built directly against IRIS in the last hours
and never exported. Six other classes existed only on disk. Nothing in the toolchain compared
the two, so the divergence was invisible to everyone including the author.

Scope, deliberately narrow:
  - Only `mode=put` WITH inline `content` — that is Claude authoring a class. `mode=get`,
    deletes and compiles are untouched.
  - A class named `<Pkg>.<Tipo>.<Name>` is gated ALWAYS — that is real interop work by the
    plugin's own convention. Anything else is gated only when the project already keeps
    sources on disk (a `src/` directory exists), so a scratch namespace stays none of this
    hook's business.

    This used to key on `src/` alone, which was the wrong way round (#107): the gate could
    only fire in a session that had already acquired the habit it exists to instil, and a
    greenfield workspace — every first put of every new project — was waved through while
    the SessionStart bootstrap advertised the gate as unconditional.
  - Classes GENERATED by IRIS (RecordMap `.Record`, SOAP wizard `WSC.*`) are exempt: they are
    produced in the namespace by design and exported afterwards.

The fix it asks for is one extra step, and it is the step that makes `src/` real: write the
file, then put the same content.
"""
import sys, json, os, re, glob

# Generated-in-IRIS artefacts: authored by a generator, exported afterwards, never hand-written.
GENERATED = re.compile(r"(?:^|\.)(?:WSC|SOAPENC)\.|\.Record$|\.Record\.cls$", re.I)

# <Pkg>.<Tipo>.<Name> — the naming convention the `interop` skill mandates and the
# conformance gate enforces. A class named this way is an interop component being
# authored, not a scratch experiment, and it belongs on disk whether or not the
# workspace has grown a src/ directory yet.
INTEROP_NAME = re.compile(r"\.(BS|BP|BO|DT|DTS|RUL|MSG|DAT|ADP|UTL|HL7)\.[^.]+$")

SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "venv", ".idea", ".vscode"}


def deny(reason):
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason,
    }}))
    sys.exit(0)


def project_root():
    return os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()


def has_source_tree(root):
    """True when this project keeps .cls sources on disk."""
    for pat in ("src", "*/src", "*/*/src", "*/*/*/src"):
        for d in glob.glob(os.path.join(root, pat)):
            if os.path.isdir(d):
                return True
    return False


def on_disk(root, cls):
    """True if a file for this class exists anywhere under the project.

    Matches the Atelier nested layout the `interop` skill mandates
    (`src/Pkg/BO/Name.cls`) and, tolerantly, the legacy flat-dotted form.
    """
    parts = cls.split(".")
    tail = ("/" + "/".join(parts) + ".cls")                  # /Pkg/BO/Name.cls
    flat = "/" + cls + ".cls"                                # /Pkg.BO.Name.cls
    # os.walk rather than glob("**"): glob silently skips dot-directories, so a class
    # staged under one reads as missing and the gate denies a file that is right there.
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            if not fn.lower().endswith(".cls"):
                continue
            norm = os.path.join(dirpath, fn).replace("\\", "/")
            if norm.endswith(tail) or norm.endswith(flat):
                return True
    return False


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        return  # never block on a hook bug
    ti = data.get("tool_input", {}) or {}
    if ti.get("mode") != "put":
        return
    content = ti.get("content")
    if not isinstance(content, str) or not content.strip():
        return
    name = str(ti.get("name") or "").strip()
    if not name:
        return
    cls = re.sub(r"\.cls$", "", name, flags=re.I)
    if not cls or GENERATED.search(name):
        return

    root = project_root()
    if not has_source_tree(root) and not INTEROP_NAME.search(cls):
        # Scratch namespace, no source tree, and the class is not named like an interop
        # component -> genuinely none of this hook's business.
        #
        # But `has_source_tree` alone was a hole, and it was the wrong way round: the gate
        # could only fire in a session that had ALREADY acquired the habit it exists to
        # instil. A greenfield workspace — no src/ yet, which is every first put of every
        # new project — was waved through, while the SessionStart bootstrap advertised the
        # gate as unconditional. `mkdir src`, which creates nothing, was the difference
        # between off and on (#107).
        #
        # A class named <Pkg>.<Tipo>.<Name> is real interop work by the plugin's own
        # convention, so it is gated from the first put. Anything else keeps the original
        # scratch exemption.
        return
    if on_disk(root, cls):
        return

    rel = "src/" + cls.replace(".", "/") + ".cls"
    deny(
        "Source-of-truth: `" + cls + "` would exist only in the IRIS namespace. No file for it "
        "was found under this project, and the namespace is not version-controlled, not "
        "reviewable, and does not survive the instance.\n\n"
        "Write the class to disk FIRST, then put the same content:\n"
        "  1. Write  " + rel + "   (Atelier nested layout: one directory per package level)\n"
        "  2. iris_doc(mode=put, name=\"" + cls + ".cls\", content=<same content>)\n\n"
        "Measured on a real workshop VM: 28 classes on disk, 29 in IRIS, 22 in common — seven "
        "existed only in the namespace, including a complete HL7 flow. Nothing compared the two, "
        "so nobody noticed. (Generated artefacts — RecordMap `.Record`, SOAP `WSC.*` — are exempt "
        "and are exported after generation instead.)"
    )


if __name__ == "__main__":
    main()
