#!/usr/bin/env python3
"""PreToolUse gate: the filesystem is the source of truth (iris-interop-skills).

`iris_doc(mode=put, content=...)` writes a class straight into the IRIS namespace. If the
class is not also on disk, the namespace becomes the only copy — it is outside git, outside
review, and it dies with the instance. This gate denies such a write when the project keeps
sources on disk and the class is missing from it.

Why this is not theoretical. Audited one student VM at the end of a workshop:

    28 classes on disk, 29 in IRIS, only 22 in common.

Seven classes existed ONLY in the namespace, and they were not scratch work — they were the
entire HL7 canonical flow (HL7ToCanonico -> MSG.PacienteCanonico -> CanonicoToMenu /
CanonicoToSOAP, plus AL1ToString and its test), built directly against IRIS in the last hours
and never exported. Six other classes existed only on disk. Nothing in the toolchain compared
the two, so the divergence was invisible to everyone including the author.

Scope, deliberately narrow:
  - Only `mode=put` WITH inline `content` — that is Claude authoring a class. `mode=get`,
    deletes and compiles are untouched.
  - Only when the project already keeps sources on disk (a `src/` directory exists). A
    scratch namespace with no source tree is none of this hook's business.
  - Classes GENERATED by IRIS (RecordMap `.Record`, SOAP wizard `WSC.*`) are exempt: they are
    produced in the namespace by design and exported afterwards.

The fix it asks for is one extra step, and it is the step that makes `src/` real: write the
file, then put the same content.
"""
import sys, json, os, re, glob

# Generated-in-IRIS artefacts: authored by a generator, exported afterwards, never hand-written.
GENERATED = re.compile(r"(?:^|\.)(?:WSC|SOAPENC)\.|\.Record$|\.Record\.cls$", re.I)


def deny(reason):
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason,
    }}))
    sys.exit(0)


def project_root():
    return os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()


def has_source_tree(root):
    """True when this project keeps .cls sources on disk."""
    for pat in ("src", "*/src", "*/*/src", "*/*/*/src"):
        for d in glob.glob(os.path.join(root, pat)):
            if os.path.isdir(d):
                return True
    return False


def on_disk(root, cls):
    """True if a file for this class exists anywhere under the project.

    Matches the Atelier nested layout the `interop` skill mandates
    (`src/Pkg/BO/Name.cls`) and, tolerantly, the legacy flat-dotted form.
    """
    parts = cls.split(".")
    tail = os.path.join(*parts) + ".cls"                     # Pkg/BO/Name.cls
    flat = cls + ".cls"                                      # Pkg.BO.Name.cls
    for path in glob.iglob(os.path.join(root, "**", "*.cls"), recursive=True):
        norm = path.replace("\\", "/")
        if norm.endswith("/" + tail.replace("\\", "/")) or norm.endswith("/" + flat):
            return True
    return False


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        return  # never block on a hook bug
    ti = data.get("tool_input", {}) or {}
    if ti.get("mode") != "put":
        return
    content = ti.get("content")
    if not isinstance(content, str) or not content.strip():
        return
    name = str(ti.get("name") or "").strip()
    if not name:
        return
    cls = re.sub(r"\.cls$", "", name, flags=re.I)
    if not cls or GENERATED.search(name):
        return

    root = project_root()
    if not has_source_tree(root):
        return  # no source tree in play
    if on_disk(root, cls):
        return

    rel = "src/" + cls.replace(".", "/") + ".cls"
    deny(
        "Source-of-truth: `" + cls + "` would exist only in the IRIS namespace. No file for it "
        "was found under this project, and the namespace is not version-controlled, not "
        "reviewable, and does not survive the instance.\n\n"
        "Write the class to disk FIRST, then put the same content:\n"
        "  1. Write  " + rel + "   (Atelier nested layout: one directory per package level)\n"
        "  2. iris_doc(mode=put, name=\"" + cls + ".cls\", content=<same content>)\n\n"
        "Measured on a real workshop VM: 28 classes on disk, 29 in IRIS, 22 in common — seven "
        "existed only in the namespace, including a complete HL7 flow. Nothing compared the two, "
        "so nobody noticed. (Generated artefacts — RecordMap `.Record`, SOAP `WSC.*` — are exempt "
        "and are exported after generation instead.)"
    )


if __name__ == "__main__":
    main()
