#!/usr/bin/env python3
"""PreToolUse gate: the filesystem is the source of truth (iris-interop-skills).

`iris_doc(mode=put, content=...)` writes a class straight into the IRIS namespace. If the
class is not also on disk, the namespace becomes the only copy — it is outside git, outside
review, and it dies with the instance. This gate denies such a write when the project keeps
sources on disk and the class is missing from it.

Why this is not theoretical. Audited one student VM at the end of a workshop:

    28 classes on disk, 29 in IRIS, only 22 in common.

Seven classes existed ONLY in the namespace, and they were not scratch work — they were the
entire HL7 canonical flow (HL7ToCanonico -> MSG.PacienteCanonico -> CanonicoToMenu /
CanonicoToSOAP, plus AL1ToString and its test), built directly against IRIS in the last hours
and never exported. Six other classes existed only on disk. Nothing in the toolchain compared
the two, so the divergence was invisible to everyone including the author.

Scope, deliberately narrow:
  - Only `mode=put` WITH inline `content` — that is Claude authoring a class. `mode=get`,
    deletes and compiles are untouched.
  - A class named `<Pkg>.<Tipo>.<Name>` is gated ALWAYS — that is real interop work by the
    plugin's own convention. Anything else is gated only when the project already keeps
    sources on disk (a `src/` directory exists), so a scratch namespace stays none of this
    hook's business.

    This used to key on `src/` alone, which was the wrong way round (#107): the gate could
    only fire in a session that had already acquired the habit it exists to instil, and a
    greenfield workspace — every first put of every new project — was waved through while
    the SessionStart bootstrap advertised the gate as unconditional.
  - Classes GENERATED by IRIS (RecordMap `.Record`, SOAP wizard `WSC.*`) are exempt: they are
    produced in the namespace by design and exported afterwards.

The fix it asks for is one extra step, and it is the step that makes `src/` real: write the
file, then put the same content.
"""
import sys, json, os, re

# Generated-in-IRIS artefacts: authored by a generator, exported afterwards, never hand-written.
GENERATED = re.compile(r"(?:^|\.)(?:WSC|SOAPENC)\.|\.Record$|\.Record\.cls$", re.I)

# <Pkg>.<Tipo>.<Name> — the naming convention the `interop` skill mandates and the
# conformance gate enforces. A class named this way is an interop component being
# authored, not a scratch experiment, and it belongs on disk whether or not the
# workspace has grown a src/ directory yet.
INTEROP_NAME = re.compile(r"\.(BS|BP|BO|DT|DTS|RUL|MSG|DAT|ADP|UTL|HL7)\.[^.]+$")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    import iis_scope
except Exception:
    iis_scope = None    # a broken sibling must not make this gate crash or deny wrongly


def deny(rule, reason):
    """Deny with a stable leading marker (#162) -- see interop_conformance_gate.deny."""
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": "[IIS-SRC-" + rule + "] " + reason,
    }}))
    sys.exit(0)


def project_root():
    return os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()


def has_source_tree(root):
    """True when this project keeps .cls sources on disk.

    Delegates to iis_scope so "what counts as a source root" has exactly one definition
    across the three hooks that ask (#401) -- including a project that declares its own in
    `.claude/iis-source-roots` because its sources are not under `src/`.
    """
    if iis_scope is None:
        return False
    return iis_scope.scoped(root)


def _match(paths, cls):
    """The first path that names this class, or None.

    Matches the Atelier nested layout the `interop` skill mandates (`src/Pkg/BO/Name.cls`)
    and, tolerantly, the legacy flat-dotted form.
    """
    tail = "/" + "/".join(cls.split(".")) + ".cls"           # /Pkg/BO/Name.cls
    flat = "/" + cls + ".cls"                                # /Pkg.BO.Name.cls
    for path in paths:
        norm = path.replace("\\", "/")
        if norm.endswith(tail) or norm.endswith(flat):
            return norm
    return None


def on_disk(root, cls):
    """(found_in_source_root, path_found_elsewhere).

    Before #401 this searched the WHOLE project and any hit counted. A demo project that
    keeps a reset seed beside `src/` -- `seed/diet/Diet/BO/Login.cls` -- therefore satisfied
    the gate with nothing written to `src/` at all, which is the one thing this gate exists
    to prevent. Now the question is asked of the project's SOURCE ROOTS.

    The second element is the whole difference between a useful deny and a baffling one. If
    a copy exists outside the source root, say where -- otherwise the message claims "no
    file was found" while the model is looking straight at one, which is how a gate earns a
    line in someone's CLAUDE.md telling the model to ignore it.
    """
    if iis_scope is None:
        return True, None       # degrade to allowing, never to denying on a hook bug
    hit = _match(iis_scope.walk_files(root), cls)
    if hit:
        return True, None
    if not iis_scope.scoped(root):
        return False, None      # nothing was narrowed, so "elsewhere" has no meaning
    return False, _match(iis_scope.walk_files(root, whole_project=True), cls)


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        return  # never block on a hook bug
    ti = data.get("tool_input", {}) or {}
    if ti.get("mode") != "put":
        return
    content = ti.get("content")
    if not isinstance(content, str) or not content.strip():
        return
    name = str(ti.get("name") or "").strip()
    if not name:
        return
    cls = re.sub(r"\.cls$", "", name, flags=re.I)
    if not cls or GENERATED.search(name):
        return

    root = project_root()
    if not has_source_tree(root) and not INTEROP_NAME.search(cls):
        # Scratch namespace, no source tree, and the class is not named like an interop
        # component -> genuinely none of this hook's business.
        #
        # But `has_source_tree` alone was a hole, and it was the wrong way round: the gate
        # could only fire in a session that had ALREADY acquired the habit it exists to
        # instil. A greenfield workspace — no src/ yet, which is every first put of every
        # new project — was waved through, while the SessionStart bootstrap advertised the
        # gate as unconditional. `mkdir src`, which creates nothing, was the difference
        # between off and on (#107).
        #
        # A class named <Pkg>.<Tipo>.<Name> is real interop work by the plugin's own
        # convention, so it is gated from the first put. Anything else keeps the original
        # scratch exemption.
        return
    found, elsewhere = on_disk(root, cls)
    if found:
        return

    rel = iis_scope.conventional_path(root, cls) if iis_scope \
        else "src/" + cls.replace(".", "/") + ".cls"

    # Two different situations, and conflating them is what made this gate ignorable. "No
    # file anywhere" is the original case. "A file exists but outside the source root" is
    # #401: the model has written something, so telling it nothing was found reads as a
    # broken hook rather than a rule.
    if elsewhere:
        where = os.path.relpath(elsewhere, os.path.normpath(root)).replace(os.sep, "/")
        # The escape hatch takes a DIRECTORY, so name the directory, not the file. Strip the
        # class's own <Pkg>/<Tipo>/<Name>.cls tail off the hit and what is left is exactly the
        # root that would make it resolve -- `seed/diet` for `seed/diet/Diet/BO/Login.cls`.
        # Telling someone to declare a .cls path in a roots file is advice that cannot be
        # followed, which is the same defect as the remedy this issue is about.
        tail = "/".join(cls.split(".")) + ".cls"
        cand = where[:-len(tail)].rstrip("/") if where.endswith(tail) else os.path.dirname(where)
        cand = cand or "."
        situation = (
            "Source-of-truth: `" + cls + "` has a file at `" + where + "`, but that is OUTSIDE "
            "this project's source root. A copy there is not the source of truth -- a seed, a "
            "fixture or an export can be restored, regenerated or deleted without anyone "
            "noticing the live class went with it.\n\n"
            "If `" + cand + "` is genuinely where this project keeps its sources, add that "
            "directory to `.claude/iis-source-roots` (one per line) and this gate will accept "
            "it. To keep a seed or fixture tree out of these checks entirely, list it in "
            "`.claude/iis-ignore`.\n\n"
        )
    else:
        situation = (
            "Source-of-truth: `" + cls + "` would exist only in the IRIS namespace. No file for "
            "it was found under this project's source root, and the namespace is not "
            "version-controlled, not reviewable, and does not survive the instance.\n\n"
        )

    deny(
        "DISK",
        situation +
        "Write the class to disk FIRST, then put the same content:\n"
        "  1. Write  " + rel + "   (Atelier nested layout: one directory per package level)\n"
        "  2. iris_doc(mode=put, name=\"" + cls + ".cls\", content=<same content>)\n\n"
        "Measured on a real workshop VM: 28 classes on disk, 29 in IRIS, 22 in common — seven "
        "existed only in the namespace, including a complete HL7 flow. Nothing compared the two, "
        "so nobody noticed. (Generated artefacts — RecordMap `.Record`, SOAP `WSC.*` — are exempt "
        "and are exported after generation instead.)"
    )


if __name__ == "__main__":
    main()
